<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Excercises filter input_filter-exerci_ee1ae2</name>
   <tag></tag>
   <elementGuidId>066be868-9d17-4001-a33e-0d974f844804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-exercises-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filter-exercises-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c47d023-648b-49e7-9ab3-9ef5a5af2ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-exercises-input</value>
      <webElementGuid>c950e413-53f2-4704-a5ce-a0a5769d18b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_exercises')</value>
      <webElementGuid>481644c3-823b-4eea-b7fa-2f2d6b704a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f120c462-2a2e-42b5-9cd7-dc4700c23bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>aa2beef9-5ecb-42ce-8e3e-f00249e54f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>1fc1ad3a-47a4-4e96-a7f8-86b209a0454e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Exercises filter bar</value>
      <webElementGuid>833c5ef7-e593-4a31-8c97-17eebd5f8a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-exercises-input&quot;)</value>
      <webElementGuid>efb84227-b928-472d-8730-3ae77a6aaca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-exercises-input']</value>
      <webElementGuid>0c783db3-974f-48fd-b0e3-bf730787a901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exercises_list']/div/div[2]/div/input</value>
      <webElementGuid>92c2fa12-7954-43a9-965f-ac07502e4429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>cc0c60a9-09b2-48d4-9ae0-f33fdae1f8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-exercises-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>f178c638-8641-4fe9-9ae6-21680f15ea99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
