<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter field for certifications_filte_73e64a</name>
   <tag></tag>
   <elementGuidId>54c490dd-5baf-44a9-b36e-e3db4ff1f00a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-certified-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filter-certified-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b63c0024-72a9-46eb-bd1d-a957ce8cd037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-certified-input</value>
      <webElementGuid>aa33485a-3403-4450-ae9d-0482530df1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_certified')</value>
      <webElementGuid>23174df2-1a7a-4c28-9432-bec00f7b085e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51700de2-3e4e-43d5-992e-dce2b9899774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>471ca88b-dd65-4b7f-b073-3f594d8027c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>c87790a2-07ce-4fcc-9ba3-9e139bac3a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Certificate filter bar</value>
      <webElementGuid>b6897cfc-4cd0-47b9-9b07-598b1cfd1408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-certified-input&quot;)</value>
      <webElementGuid>5c618b0d-9005-4b21-aea5-3dff79a5d718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-certified-input']</value>
      <webElementGuid>2151fc8a-ee93-4bbc-a2cc-e8cb05f12183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='certified_list']/div/div[2]/div/input</value>
      <webElementGuid>bbcb19e4-778f-4705-aeef-cfbce103723d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>09c91746-fa87-499d-8c0a-00cff0214297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-certified-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>4bdefe6c-1439-423c-954f-5e3ad3b779a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
