<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Clone in Webflow_css-wtpnzt</name>
   <tag></tag>
   <elementGuidId>3db9f163-c199-43db-8ad1-6448493898b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/main/div/div/div/div[2]/div[2]/div/div/div/div[2]/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.css-wtpnzt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f1904d58-61d2-4577-ae0e-6760b885c51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vimeo-background-video-play-button.webflow.io</value>
      <webElementGuid>88dbb99d-d4e1-41a1-9d00-5504162380dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Vimeo Background Video with Play Sound Toggle</value>
      <webElementGuid>6adee932-6ebf-4c1f-bf9b-74c1cd01ce44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7272dde1-6870-4888-881e-6e3ae6bee754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-scripts</value>
      <webElementGuid>c5cdd66a-ee31-4d97-9389-2d70a48828e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>61559f17-e191-4eee-ad4b-459210dc6cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-wtpnzt</value>
      <webElementGuid>f1b95fa5-c7b3-42e8-8d7b-8cdc0b78c38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;wf-17llzd4&quot;]/div[@class=&quot;wf-wapbv3&quot;]/div[1]/main[@class=&quot;wf-1rzwxxs --styled-kSaIEv wf-tywzh5&quot;]/div[@class=&quot;wf-1rzwxxs --styled-gaQrdW wf-1c9u7m2&quot;]/div[@class=&quot;wf-1rzwxxs --styled-gaQrdW wf-1c9u7m2&quot;]/div[@class=&quot;wf-1rzwxxs --styled-gaQrdW wf-1c9u7m2&quot;]/div[@class=&quot;wf-1rzwxxs --styled-jsSPoM wf-i973ku&quot;]/div[@class=&quot;wf-1rzwxxs --styled-cuQdeD wf-7f2tz8&quot;]/div[@class=&quot;css-rlulsa&quot;]/div[@class=&quot;css-5xiw9o&quot;]/div[@class=&quot;wf-1rzwxxs --styled-tLgHU wf-hlyxds&quot;]/div[@class=&quot;wf-1rzwxxs --styled-fCTRWd wf-1of9lyh&quot;]/iframe[@class=&quot;css-wtpnzt&quot;]</value>
      <webElementGuid>3502a49b-18ec-46b6-90ad-db704364394f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/main/div/div/div/div[2]/div[2]/div/div/div/div[2]/iframe</value>
      <webElementGuid>6b8dc502-ed8a-41c9-8822-b7f4df3a6b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>84446898-2b2a-4a71-acf5-758753a99cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://vimeo-background-video-play-button.webflow.io' and @title = 'Vimeo Background Video with Play Sound Toggle']</value>
      <webElementGuid>fb383d0d-6c3f-4151-b88a-9f8181109d4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
