<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Run</name>
   <tag></tag>
   <elementGuidId>2acca612-ed98-4096-b76b-c0c58c941a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='runbtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#runbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>055a5822-775f-492d-9dfa-1ee2dbd972f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runbtn</value>
      <webElementGuid>e5143324-b714-4a82-914e-0000513677a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-button w3-bar-item w3-hover-white w3-hover-text-green ga-tryit</value>
      <webElementGuid>37e7ea4b-49d0-4285-91d1-ab00715bea30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submitTryit(1);uic_r_p();</value>
      <webElementGuid>46151247-22b5-4b76-b057-5c88ed25ed31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Run ❯</value>
      <webElementGuid>ae94567f-838f-4296-b039-3625a4498f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runbtn&quot;)</value>
      <webElementGuid>7cd83281-77e1-473a-8cb2-e3199371fc44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='runbtn']</value>
      <webElementGuid>ab03e014-d9b3-475c-9d4d-19a20891aa83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tryit: HTML iframe'])[1]/following::button[1]</value>
      <webElementGuid>499cfef8-b2a2-4c7b-9f50-41f2e0d8494c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML Iframes'])[1]/following::button[1]</value>
      <webElementGuid>071c0346-2c30-43a9-84c3-e4a2f7ea2165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='own'])[1]/preceding::button[1]</value>
      <webElementGuid>436f0db2-e9b7-4da5-911c-7577f9028987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Run ❯']/parent::*</value>
      <webElementGuid>3e2bb76e-4d23-4efd-b67b-b85f5e99c174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>09f83d67-d50e-4537-aa6b-0d6b9fc7a65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'runbtn' and (text() = 'Run ❯' or . = 'Run ❯')]</value>
      <webElementGuid>299da1fd-a1d9-400c-897c-a4745e8cdccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
